
<p align="center">
  如果这个项目对您有所帮助，欢迎请我喝杯咖啡，支持后续维护和更新。
</p>

<p align="center">
  <img src="https://github.com/naoki66/XR1710G-http-uboot/raw/2026-8-11-b7710e5cc851/c6ea388c976395326514814f80d512d5.png" alt="Donate" width="240">
</p>
